extra:
  search:
    language: 'en, pt'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences

nav:
- Introdução: index.md
- Aula 1 (2019-04-02): aula1.md
- Aula 2 (2019-04-04): aula2.md
- Aula 3 (2019-04-09): aula3.md
- Aula 4 (2019-04-11): aula4.md
- Aula 5 (2019-04-16): aula5.md
- Exercícios 1: exercicios1.md

plugins:
  - search

site_name: Banco de dados
site_description: Disciplina de banco de dados
site_author: Allainclair Flausino dos Santos
site_url: https://github.com/allainclair

theme:
  language: pt
  name: material